server:
  port: 8089
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dlyk?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 0801
    hikari:
      maximum-pool-size: 30
      minimum-idle: 20
      connection-timeout: 5000
      idle-timeout: 0
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: qiao
      database: 0
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  mapper-locations: classpath:mapper/*.xml


